import animation from './includes/animation.js';
import dataToggle from './includes/dataToggle.js';
import dataTrigger from './includes/dataTrigger.js';
import mobileNav from './includes/mobileNav.js';
import photoSwipe from './includes/photoSwipe.js';
import headerScroll from './includes/headerScroll.js';
import projectsSlider from './includes/projectsSlider.js';
import partnersSlider from './includes/partnersSlider.js';
import placeholder from './includes/placeholder.js';
import orderFormValidation from './includes/orderFormValidation.js';
import orderForm2Validation from './includes/orderForm2Validation.js';
import imask from './includes/imask.js';
import productSlider from './includes/productSlider.js';
import loadMoreDescr from './includes/loadMoreDescr.js';
import tabs from './includes/tabs.js';
import filter from './includes/filter.js';
import customCursor from './includes/customCursor.js';
import modal from './includes/modal.js';
import '../sass/main.sass';


animation();
dataToggle();
dataTrigger();
mobileNav();
photoSwipe();
headerScroll();
projectsSlider();
partnersSlider();
placeholder();
orderFormValidation();
orderForm2Validation();
imask();
productSlider();
loadMoreDescr();
tabs();
filter();
customCursor();
modal();
